language: php

php:
  - 7.2
  - 7.1
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit

